name: matrix-configuration
on: 
  workflow_dispatch:

jobs:
  deploy-on-multiple-os:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04]
        images: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker details
        run: docker info
      - name: Running docker images ${{ matrix.images }} on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
